### ISSUE TITLE
Add a compiled build to download

### ISSUE THREAD

**Issue by asdfMaciej** [mati9344/Librus-Synergia#1]
I'm interested in this project, but I don't have the tools to compile it. It'd be great if you compiled the latest version and added a link to it in readme.

On a sidenote - did the introduction of the new Synergia application by Librus team change how the API works? (as the old application doesn't work anymore, and some 3rd party ones aswell)

**Comment by mati9344** [comment]
I'll provide compiled files this weekend.

Api in this project downloads and parses HTML directly from Synergia website. Any changes which don't affect website are safe for the api. I just tested it out and everything works fine.

Btw this project is quite old. I think it needs some refactoring. Let me know if you want to contribute - if so I'll review and refactor the code a little.

**Comment by asdfMaciej** [comment]
Oh, I see. I won't be able to contribute, as I don't know C# and not planning to learn it in upcoming time (picking up Java recently). Good job on the HTML parser, I tried developing the same exact solution in Python at start of this year. It worn me out so bad that I didn't finish it.

**Comment by mati9344** [comment]
Website code is really terrible to parse, therefore API code quality is so bad.
I added compiled source to readme

**Comment by asdfMaciej** [comment]
Thank you! It looks really nice, I'll keep an eye on this project, it'd be useful :)
