### ISSUE TITLE
Use the Synergia REST API instead of scraping

### ISSUE THREAD

**Issue by Frioo** [mati9344/Librus-Synergia#2]
Cześć, proponuję pomoc, na swoim githubie mam mały sneak-peak API librusa, niedługo szykuję większe zmiany. Wchodzisz w to? Aplikacje desktopową też chciałem napisać :)

**Comment by mati9344** [comment]
Cześć, wybacz za takie opóźnienie 
Aktualnie nie mam Windowsa, ale jak już go zdobędę to chętnie użyję Twojego API ;)

**Comment by Frioo** [comment]
Jasne! Pisz jak będziesz gotowy.

**Comment by mati9344** [comment]
Windows gotowy.
Przepiszę całą aplikację od nowa z użyciem tego API. Za duży bałagan się zrobił i będzie po prostu łatwiej.

**Comment by Frioo** [comment]
Dzięki za odpowiedź.
API nie jest jeszcze w pełni gotowe - brakuje planu lekcji i wiadomości.
Zawsze możesz jakoś pomóc jeśli czujesz się na siłach, ale ja też niedługo postaram się dokończyć pisanie modeli danych.

**Comment by mati9344** [comment]
Zobaczę jak mi czasu wystarczy, ale się postaram 😄
